name: mubin_orders
description: "mubin_orders"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  appinio_social_share: ^0.3.1
  cached_network_image: ^3.3.1
  cached_video_player_plus: ^3.0.3
  camera: ^0.11.1
  chewie: ^1.8.1
  country_flags: ^3.2.0
  country_icons: ^3.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  delightful_toast: ^1.1.0
  dio: ^5.8.0+1
  dough: ^2.0.0
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.3
  file_picker: ^8.0.2
  file_selector: ^1.0.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  flutter_bloc: ^9.0.0
  flutter_localization: ^0.3.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  list_all_videos: ^1.2.0
  local_auth: ^2.2.0
  location: ^8.0.0
  material_dialogs: ^1.1.4
  motion_toast: ^2.11.0
  open_file: ^3.3.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  salomon_bottom_bar: ^3.3.2
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  shimmer_effect: ^1.0.4
  simple_circular_progress_bar: ^1.0.2
  sqflite: ^2.3.3
  staggered_grid_view_flutter: ^0.0.4
  url_launcher: ^6.2.6
  video_player: ^2.8.6
  video_player_win: ^3.1.1
  whatsapp_share: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  package_rename: ^1.7.1
  retrofit_generator: ">=8.0.0 <10.0.0"
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    # /mbean_logo_circale.png
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: true
