name: mubin_orders
description: "mubin_orders"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  appinio_social_share: ^0.3.1
  cached_network_image: ^3.3.1
  cached_video_player_plus: ^2.0.0
  camera: ^0.10.5+9
  chewie: ^1.8.1
  country_flags: ^2.2.0
  country_icons: ^3.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.5
  delightful_toast: ^1.1.0
  dio: ^5.8.0+1
  dough: ^2.0.0
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.3
  file_picker: ^8.0.2
  file_selector: ^1.0.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.2.0
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.1.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^8.0.3
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.2.8
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  list_all_videos: ^1.2.0
  local_auth: ^2.2.0
  location: ^6.0.1
  material_dialogs: ^1.1.4
  motion_toast: ^2.11.0
  open_file: ^3.3.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  salomon_bottom_bar: ^3.3.2
  screenshot: ^2.3.0
  share_plus: ^10.1.4
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  shimmer_effect: ^1.0.4
  simple_circular_progress_bar: ^1.0.2
  sqflite: ^2.3.3
  staggered_grid_view_flutter: ^0.0.4
  step_progress_indicator: ^1.0.2
  timezone: ^0.9.2
  url_launcher: ^6.2.6
  video_compress: ^3.1.2
  video_compress_plus: ^1.0.0
  video_player: ^2.8.6
  video_player_win: ^2.3.6
  webview_flutter: ^4.7.0
  whatsapp_share: ^2.0.2
dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  package_rename: ^1.7.1
  retrofit_generator: ">=8.0.0 <10.0.0"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mbean_logo_circale.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
