name: mbean_talabat
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  cached_network_image: ^3.3.1
  cached_video_player_plus: ^2.0.0
  camera: ^0.10.5+9
  chewie: ^1.8.1
  dio: ^5.8.0+1
  cupertino_icons: ^ 1.0.6
  dartz: ^0.10.1
  delightful_toast: ^1.1.0
  equatable: ^2.0.5
  file_picker: ^8.0.7
  file_selector: ^1.0.3
  firebase_auth: ^5.2.0
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.2.0
  flutter_inappwebview: ^6.0.0
  flutter_localization: ^0.2.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  local_auth: ^2.2.0
  location: ^6.0.1
  material_dialogs: ^1.1.4
  motion_toast: ^2.11.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  salomon_bottom_bar: ^3.3.2
  share_plus: ^8.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  shimmer_effect: ^1.0.4
  url_launcher: ^6.2.6
  video_compress_plus: ^1.0.0
  video_player: ^2.8.6
  webview_flutter: ^4.7.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.13
  flutter_native_splash: ^2.4.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  package_rename: ^1.7.1
  retrofit_generator: ">=8.0.0 <10.0.0"
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mbean_logo_circale.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/mbean_logo_circale.png"
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/mbean_logo_circale.png
flutter_intl:
  enabled: true
