// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8y_TA_TCHYhiOzJyE_Svx_NU-AT3BVwE',
    appId: '1:422502425305:web:d59fd180e8de9a4dfe54c8',
    messagingSenderId: '422502425305',
    projectId: 'test-5bd42',
    authDomain: 'test-5bd42.firebaseapp.com',
    storageBucket: 'test-5bd42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZo2vDoCEEVVsoodSoWx14IPWCRWkKxjw',
    appId: '1:422502425305:android:f9ac9ab624f94375fe54c8',
    messagingSenderId: '422502425305',
    projectId: 'test-5bd42',
    storageBucket: 'test-5bd42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG0PynVPRhyVjbEQw6Vc_AchfezCCh8Uo',
    appId: '1:422502425305:ios:4dc513fe324bb9b8fe54c8',
    messagingSenderId: '422502425305',
    projectId: 'test-5bd42',
    storageBucket: 'test-5bd42.appspot.com',
    iosBundleId: 'com.example.meshwar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG0PynVPRhyVjbEQw6Vc_AchfezCCh8Uo',
    appId: '1:422502425305:ios:4dc513fe324bb9b8fe54c8',
    messagingSenderId: '422502425305',
    projectId: 'test-5bd42',
    storageBucket: 'test-5bd42.appspot.com',
    iosBundleId: 'com.example.meshwar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8y_TA_TCHYhiOzJyE_Svx_NU-AT3BVwE',
    appId: '1:422502425305:web:67252a786d82194dfe54c8',
    messagingSenderId: '422502425305',
    projectId: 'test-5bd42',
    authDomain: 'test-5bd42.firebaseapp.com',
    storageBucket: 'test-5bd42.appspot.com',
  );
}
